### ISSUE TITLE
`.section-year`に`flex-shrink: 0;`を設定する

### ISSUE THREAD

**Issue by SnO2WMaN** [rinsuki/myanimecovers#1]
## 問題

縮んでてよくない

![image](https://user-images.githubusercontent.com/15155608/213062305-ef04ee54-a51e-48fa-a1b6-bb7aa055f8b3.png)

## 解決策

`.section-year`に`flex-shrink: 0;`を設定する

![image](https://user-images.githubusercontent.com/15155608/213062475-ca87d178-7d28-4a7a-b90c-781656afd154.png)

もう少し良い解決案があるかもしれませんが…

**Comment by rinsuki** [comment]
単純にFirefoxの初回レイアウトが壊れているので flex-shrink じゃだめっぽい
